server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: gb
    password: gb

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

cos:
  key: cos1234